
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate
  
homeassistant:
  packages: !include_dir_named include
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

# logger:
#   default: debug

automation: !include automations.yaml
# binary_sensor: !include_dir_list configs/binary_sensors
# cover: !include_dir_list configs/covers
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
# sensor: !include_dir_list configs/sensors
# switch: !include_dir_list configs/switches

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

wake_on_lan:

ffmpeg:

browser_mod:
  prefix: 'browser_'

api:

shell_command:
  turn_off_via_ssh: ssh -F /config/ssh_config -i /config/id_rsa {{ username }}@{{ host }} 'poweroff'
  git_pull: cd /config && git pull
  git_push: cd /config && git add . && git commit -m "config files on `date +'%d-%m-%Y %H:%M:%S'`" && git push
