
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate
  
homeassistant:
  packages: !include_dir_named include
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

wake_on_lan:

ffmpeg:

browser_mod:
  prefix: 'browser_'

api:
