sensor:
  - platform: qnap
    host: !secret device_nidoran_host
    username: !secret device_nidoran_username
    password: !secret device_nidoran_password
    monitored_conditions:
      - status
      - system_temp
      - cpu_temp
      - cpu_usage
      - memory_free
      - memory_used
      - memory_percent_used
      - network_link_status
      - network_tx
      - network_rx
      - drive_smart_status
      - drive_temp
      - volume_size_free
      - volume_size_used
      - volume_percentage_used

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: memory_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
      - type: network_in # network_in_eth0
        arg: eth0
      - type: network_out # network_out_eth0
        arg: eth0
      - type: throughput_network_in # network_throughput_in_eth0
        arg: eth0
      - type: throughput_network_out # network_throughput_out_eth0
        arg: eth0