platform: template
sensors:
  boiler:
    value_template: >-
      {% set t = strptime(states('sensor.time'), '%H:%M') %}
      {% set b = states('input_select.central_boiler') %}
      {%- if b == 'On' and (6 <= t.hour <= 9 or 11 <= t.hour <= 15 or 17 <= t.hour <= 23) %}
      100
      {%- elif b == 'Partial' and (7 <= t.hour <= 9 or 18 <= t.hour <= 22) %}
      100
      {%- else %}
      0
      {%- endif %}