platform: qnap
host: !secret device_nidoran_host
username: !secret device_nidoran_username
password: !secret device_nidoran_password
monitored_conditions:
  - status
  - system_temp
  - cpu_temp
  - cpu_usage
  - memory_free
  - memory_used
  - memory_percent_used
  - network_link_status
  - network_tx
  - network_rx
  - drive_smart_status
  - drive_temp
  - volume_size_free
  - volume_size_used
  - volume_percentage_used